### ISSUE TITLE
process_complete_container zips up too much

### ISSUE THREAD

**Issue by djfigs1** [friendly-besties-incorporated/all-honeypot-code#24]
Hard to describe, but it seems like the the ZIP operation is trying to zip the _entire_ container file system. 

![image](https://user-images.githubusercontent.com/9463387/194779785-1d426a6d-993b-4dbc-aab1-d7d2e9dd234b.png)

**Comment by sysemenova** [comment]
Huh, it def shouldn't be doing that. I'll check it
